### ISSUE TITLE
Can't find module via zef, not sure how to install

### ISSUE THREAD

**Issue by johnsaigle** [japhb/CBOR-Simple#1]
Hi there,
I became aware of this package because I was trying to install [Cro](https://cro.services/), which lists this package as a dependency.

However, I can't install CBOR::Simple (or Cro) via `zef` because it seems unable to find it:

```
zef install Cro::HTTP  
===> Searching for: Cro::HTTP
===> Searching for missing dependencies: IO::Socket::Async::SSL, OO::Monitors, IO::Path::ChildSecure, Base64, HTTP::HPACK, Cro::Core:ver<0.8.6>, Cro::TLS:ver<0.8.6>, JSON::Fast, Crypt::Random, JSON::JWT, DateTime::Parse, Log::Timeline
===> Searching for missing dependencies: MIME::Base64, OpenSSL, Digest::HMAC, if, CBOR::Simple
===> Failed to find dependencies: CBOR::Simple
Failed to resolve some missing dependencies
```

Do you have a suggestion for another way to install the module? I'm new to the Raku ecosystem.

See also: https://stackoverflow.com/questions/69842180/difficulties-installing-cro-failed-to-find-dependencies-cborsimple

**Comment by Scimon** [comment]
Hi John I saw this issue raised and I think you asked the same question in StackOverflow? Looking at it the module is *only* available in the new fez repository system. I'm guessing you have an older version for `zef` that doesn't know about the existence of fez.
I'd advise updating your zef version `zef upgrade zef` should do the trick.

**Comment by japhb** [comment]
That's unexpected.  Let's try remote diagnosis:

* What do you get for `raku -v` and `zef --version`?
* If you run `zef update`, do you see a line that says `===> Updated fez mirror: http://360.zef.pm/`?
* What does `zef info CBOR::Simple` say, after you do the `zef update`?
* ... also what @Scimon said; he beat me to the punch.

**Comment by japhb** [comment]
I see you mentioned your `zef` version on IRC, and someone already mentioned it's too old, and where to get newer packages.

Closing this particular issue here, because we all seem to have reached the same conclusion in 3 different forums, so I'm going to reduce that by one.

**Comment by johnsaigle** [comment]
Thank you for the advice. I'm not getting the issue anymore with a newer version of zef.
